### PR TITLE
Improve conditional Asset loading

### PR DESCRIPTION
**Pull request by kraftner**
First step toward fixing #61 

This is not yet complete as similar checks would need to be added for the term edit screen. Probably checks found in https://github.com/Yoast/wordpress-seo/blob/d5490d798a8c0ecd4a28805e2786c548a9a02b57/admin/taxonomy/class-taxonomy.php

### CODE REVIEW

**Comment by kraftner** [comment]
Also it seems that moving the script to the footer breaks the listener for changes. Maybe due to [`ready`](https://github.com/Yoast/yoast-acf-analysis/blob/develop/js/src/app.js#L22) already being fired at the point the script runs.

**Comment by herregroen** [comment]
Just throwing around some ideas here:
* We could check if the handle for `wpseoPostScraperL10n` is enqueued: `wp_script_is( WPSEO_Admin_Asset_Manager::PREFIX . 'post-scraper' )`.
* We could localize `wpseoPostScraperL10n` ourselves, the object can be retrieved with `$GLOBALS['wpseo_metabox']->localize_post_scraper_script()`.

**Comment by kraftner** [comment]
Thanks @herregroen for the idea. I moved `admin_enqueue_scripts` to priority 11 to make sure we're after the main plugin. This enables using `wp_script_is()` which leads to much simpler and cleaner code.

Concerning the second proposal I think that isn't needed as that situation should now never happen and even if it still does this is now gracefully handled with [5.4.0 of Yoast SEO](https://github.com/Yoast/wordpress-seo/releases/tag/5.4.0).

I think this is now ready to be tested and merged.

**Comment by kraftner** [comment]
I guess this also fixes #21

**Pull request merged**
