### PR TITLE
Introduce travis builds

### PR DESCRIPTION
**Pull request by moorscode**
Introduces travis configuration.

Travis will check the following elements:
- [x] Coding standards
- [x] PHP linting
- [x] PHP unittests

Travis will be triggered for PRs on the following branches:
- master
- develop
- release/\*.\*
- hotfix/\*.\*

### CODE REVIEW

**Comment by moorscode** [comment]
PHP 5.x effectively only has `linting` at the moment.
This is because packages are installed in composer, which require PHP 7.1.

Addressing this in a separate issue to determine what we want to do with this.

**Comment by moorscode** [comment]
There is one failing test, making the build fail.

Which is caused by
```
1) Yoast\AcfAnalysis\Tests\MainTest::testInvalidConfig
PHP Fatal error:  A void function must not return a value in /tmp/wordpress/src/wp-content/plugins/yoast-acf-analysis/vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php on line 149
```

See:
```
Functions\expect('get_option')
			->once()
			->with('acf_version')
			->andReturn(5);
```

@kraftner do you have any insights/enlightment on how to resolve this problem?

**Comment by moorscode** [comment]
As https://github.com/Yoast/yoast-acf-analysis/pull/104 has been merged, the check in the test is no longer relevant.

It was a bit misplaced inside a test which was testing other functionality to begin with, so happy to have removed it.

**Comment by moorscode** [comment]
Will create a new issue for adding JS linting and testing.

**Comment by andizer** [comment]
Awesome :+1:

**Pull request merged**
